### ISSUE TITLE
Unable to install Grack with JRuby

### ISSUE THREAD

**Issue by 153111** [grackorg/rjgit_grack#3]
I have installed Grack with Ruby 2.5.1 with no issues and run it prefectly. 
Since rjgit_grack need rjgit gem, which requires JRuby, I switch to JRuby 9.1.17.0 using rvm. Install rjgit gem without a problem but due to redcarpet gem is incompatible with JRuby, I was unable to install grack. Redcarpet is required during the installation of [grack](https://github.com/grackorg/grack).

Here is the comment about redcarpet gem incompatibility with JRuby 
https://github.com/vmg/redcarpet/issues/594#issuecomment-270025569

Here is my question, how do we install and use rjgit_grack properly? I'm a newbie, a clear explanation would be appreciated.

Thanks in advance!

### Add-on
I have tried to install the rjgit gem with **Ruby 2.5.1** and use rjgit_grack adapter by changing my config.ru, run it with 
```sh
bundle exec rackup --host localhost --port 8080 config.ru
```
But I got the error
```
bundler: failed to load command: rackup (/home/morilab/.rvm/gems/ruby-2.5.1/bin/rackup)
LoadError: cannot load such file -- rjgit_grack
  /home/morilab/Documents/grack/config.ru:3:in `require'
  /home/morilab/Documents/grack/config.ru:3:in `block in <main>'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
  /home/morilab/Documents/grack/config.ru:in `new'
  /home/morilab/Documents/grack/config.ru:in `<main>'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/server.rb:283:in `start'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
  /home/morilab/.rvm/gems/ruby-2.5.1/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
  /home/morilab/.rvm/gems/ruby-2.5.1/bin/rackup:23:in `load'
  /home/morilab/.rvm/gems/ruby-2.5.1/bin/rackup:23:in `<top (required)>'
```

**My system**
Ubuntu 18.04 on VirutalBox
I would be happy to provide more details if required.

**Comment by bartkamphorst** [comment]
@153111 Care to explain what redcarpet has to do with grack?

**Comment by 153111** [comment]
> @153111 Care to explain what redcarpet has to do with grack?

I'm sorry for the insufficient explanation. 

Redcarpet gem is required during the installation of grack. 
According to here, [https://github.com/grackorg/grack](url), redcarpet (>= 3.1.0, ~> 3.1) is needed as written in the Development Requirements list.

rjgit_grack need rjgit and grack. rjgit require JRuby but i can't install grack with JRuby because of the redcarpet.

**Comment by bartkamphorst** [comment]
@153111 Thanks, that helps.

> Redcarpet gem is required during the installation of grack.

As you've pointed out, redcarpet is only a development dependency. As far as I'm aware, this means that you should be able to _use_ grack on JRuby without redcarpet. Could you help me understand what you are doing to install grack on JRuby? And what does your `config.ru` say?

**Comment by dometto** [comment]
Not sure what redcarpet and github-markup are doing in the development dependencies, I'll see if we can remove them. But `gem install grack` should work on jruby, as should requiring grack as a dependency in your own gemfile/gemspec.

**Comment by 153111** [comment]
@bartkamphorst. I do not have the working PC with me right now and i can't show you the error message. But i will try to explain as clearly as I can.
### My goal
I'm working on a project that requires the pre-upload hook for my git, which rjgit_grack have the thing that I want. For my understanding, to get rjgit_grack working for my project, I need to get grack and rjgit into my system.
### Installation of grack (my way. not sure if i did it correctly)
version - Ruby 2.5.1
First, use `git clone https://github.com/grackorg/grack.git` to get grack and install it using `bundle install`. I've encountered errors during the installation but solve it by using `rvm`.
Create `config.ru` and write,
```
require 'grack/app'
require 'grack/git_adapter'

config = {
  :root => '/srv/git/153111-project.git',
  :allow_push => true,
  :allow_pull => true,
  :git_adapter_factory => ->{ Grack::GitAdapter.new }
}

run Grack::App.new(config)
```
run it with `bundle exec rackup --host localhost --port 8080 config.ru` and it worked fine. Able to push and pull.
### Install rjgit_grack
`gem install rjgit_grack` & `gem install rjgit`. Then change my config.ru to, 
```
require 'grack/app'
require 'grack/git_adapter'
require 'rjgit_grack'

config = {
  :root => '/path/to/bare/repositories',
  :allow_push => true,
  :allow_pull => true,
  :git_adapter_factory => ->{ Grack::RJGitAdapter.new }
}

run Grack::App.new(config)
```
run `bundle exec rackup --host localhost --port 8080 config.ru` and get the error message that I've shown above.
### Solution to that
I install `JRuby 9.1.17` using `rvm` and  `gem install rjgit`. Then install grack with the same way that i used, this is where I get the `redcarpet incompatible with JRuby` error came in. 
I realize that redcarpet is only a development dependency so I ignore the message and make sure I have `rack` (runtime requirement) installed and run it anyway. But still, the error message of `redcarpet gem is required`and stop me from running grack.

**Comment by 153111** [comment]
@dometto Thank you!!

**Comment by 153111** [comment]
I was able to install grack in JRuby 9.1.17 with `gem install grack`. But I couldn't run it with `bundle exec rackup --host localhost --port 8080 config.ru`, show the error below,
```
Could not locate Gemfile or .bundle/ directory
```
Instead of `bundle exec rackup --host localhost --port 8080 config.ru`, I run it with `rackup --host localhost -p 8080 config.ru` and the server is up. 

After that, I install rjgit & rjgit_grack, but I encounter another error when I add `require 'rjgit_grack'` in my `config.ru` and i will post in another issue about it.
Thanks.
